# Generated by Django 4.2.3 on 2023-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_is_accepted_alter_delivery_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
