# Generated by Django 4.2.3 on 2023-08-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delivery_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
