# Generated by Django 4.2.3 on 2023-08-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
