# Generated by Django 4.2.3 on 2023-08-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='stock_left',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='stock_used',
        ),
    ]
